spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:grocerydb
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true